@startuml NOPUnreal

together {
    abstract class UObject
    abstract class AActor
    abstract class AInfo
    abstract class APawn
    abstract class UActorComponent
    class AGameModeBase
}

class FBE
class ANOPBasePawn
class ANOPPlayerPawn
class ANOPEnemyPawn
class ANOPShooterPawn
class NOPSuicidePawn
class ANOPBomberPawn
class ANOPGameMode
class ANOPEnemySpawn
class UBaseAbility

class AProjectile
class ABomb




UObject <|-- AActor
AActor <|-- APawn
UObject <|-- UActorComponent
AActor <|-- AInfo
AInfo <|-- AGameModeBase

APawn <|-- ANOPBasePawn
FBE <|-- ANOPBasePawn

AGameModeBase <|-- ANOPGameMode
FBE <|-- ANOPGameMode

AActor <|-- ANOPEnemySpawn
FBE <|-- ANOPEnemySpawn

UActorComponent <|-- UBaseAbility

AActor <|-- AProjectile
AActor <|-- ABomb

ANOPBasePawn <|-- ANOPPlayerPawn
ANOPBasePawn <|-- ANOPEnemyPawn

ANOPEnemyPawn <|-- NOPSuicidePawn
ANOPEnemyPawn <|-- ANOPShooterPawn
ANOPEnemyPawn <|-- ANOPBomberPawn

UBaseAbility <|-- FireProjectileAbility
UBaseAbility <|-- FireMissileAbility
UBaseAbility <|-- DropBombAbility

ANOPEnemySpawn "1" o-- "many" ANOPEnemyPawn
FireProjectileAbility "1" o-- "many" AProjectile
DropBombAbility "1" o-- "many" ABomb

@enduml
