@startuml tdd
skinparam backgroundcolor transparent
start
repeat
    :Adicionar testes;
    repeat :Modificar codigo;
    repeat while (Executar testes) is (falha) not (sucesso)
repeat while (Desenvolvimento finalizado) is (não) not (sim)
end

@enduml